#!/usr/bin/env python3
"""Embed the web edition's JSON data + locales into a single JS file so the
game runs by opening index.html directly (file://) with no web server.

Run from the repo root:

    python3 scripts/build_web_locales.py    # first, if strings changed
    python3 scripts/build_web_bundle.py

Writes web/js/game-bundle.js — a map of every web/data/**/*.json and
web/i18n/*.json file, keyed by the same paths js/data.js and js/i18n.js
fetch. Those loaders prefer the embedded bundle and fall back to fetch()
when it's absent, so serving over HTTP still works (and editing the JSON
files directly keeps working — just re-run this script to re-embed).
"""
import glob
import json
import os

WEB = "web"
OUT = os.path.join(WEB, "js", "game-bundle.js")


def main():
    bundle = {}
    files = sorted(
        glob.glob(os.path.join(WEB, "data", "**", "*.json"), recursive=True)
        + glob.glob(os.path.join(WEB, "i18n", "*.json"))
    )
    for path in files:
        if os.path.basename(path) == "web-keys.json":
            continue  # source file for locale generation, not loaded by the game
        # Keys mirror what the loaders fetch: paths relative to web/data/
        # ('xp_table.json', 'dungeons/farm.json') and 'i18n/<locale>.json'.
        if path.startswith(os.path.join(WEB, "data") + os.sep):
            key = os.path.relpath(path, os.path.join(WEB, "data")).replace(os.sep, "/")
        else:
            key = os.path.relpath(path, WEB).replace(os.sep, "/")
        with open(path, encoding="utf-8") as f:
            bundle[key] = json.load(f)

    parts = [
        "/* ------------------------------------------------------------------ *\n"
        " * game-bundle.js — GENERATED by scripts/build_web_bundle.py.\n"
        " * Every JSON under web/data and web/i18n embedded as one map so the\n"
        " * game boots from file:// with no web server. Don't edit by hand;\n"
        " * edit the JSON files and re-run the script instead.\n"
        " * ------------------------------------------------------------------ */\n"
        "'use strict';\n\n"
        "const GAME_BUNDLE = ",
        json.dumps(bundle, ensure_ascii=False, separators=(",", ":")),
        ";\n\n"
        "/* Export for Node-based tests (no-op in the browser) */\n"
        'if (typeof module !== "undefined" && module.exports) module.exports = { GAME_BUNDLE };\n',
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("".join(parts))
    size = os.path.getsize(OUT)
    print(f"wrote {OUT}: {len(bundle)} files, {size / 1024:.0f} KB "
          f"({sum(len(json.dumps(v, separators=(',', ':'))) for v in bundle.values()) / 1024:.0f} KB of JSON)")
    missing = [k for k in ("xp_table.json", "dungeons.json", "i18n/en.json") if k not in bundle]
    if missing:
        raise SystemExit(f"  ERROR: expected keys missing: {missing}")


if __name__ == "__main__":
    main()
